$: << File.dirname(__FILE__)
require 'ostruct'
require 'fixed_width/core_ext/symbol'
require 'fixed_width/fixed_width'
require 'fixed_width/definition'
require 'fixed_width/section'
require 'fixed_width/line_parser'
require 'fixed_width/column'
require 'fixed_width/parser'
require 'fixed_width/generator'
